version: "3"
services:
  app:
    env_file:
      - .env
    container_name: ci-cd-pipeline
    restart: always
    build: .
    ports:
      - "$PORT:$PORT"
    links:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "81:80"

volumes:
  postgres:
    driver: local