name: ci-cd-pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - stage
      - main

jobs:
  test:
    name: test nestjs
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm run test

      - name: Notify Slack on Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: ${{ github.actor }}
          channel: ${{ secrets.SLACK_CHANNEL }}
          username: ${{ secrets.SLACK_USERNAME }}
          text: "Tests failed! :x:"
        env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
