name: ci-cd-pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - stage
      - main

jobs:
  test:
    name: test nestjs
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v4.0.0

      - name: setup node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v3.3.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm run test

      - name: Notify Slack on Failure
        if: failure()
        uses: 8398a7/action-slack@v3.15.1
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: ${{ github.actor }}
          channel: ${{ secrets.SLACK_CHANNEL }}
          username: ${{ secrets.SLACK_USERNAME }}
          text: "Tests failed! :x:"
        env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  build_and_deploy:
    name: build docker image and ecs deploy
    runs-on: ubuntu-22.04
    needs: test

    steps:
      - name: checkout
        uses: actions/checkout@v4.0.0

      - name: configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ap-northeast-2
          role-to-assume: arn:aws:iam::332034673285:role/github-OIDC
          role-session-name: MyGithubOIDC

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
